title: Play With Your Food

description: Feed your inner child
author: Michael Wong
url: https://playwithyour.food

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:slug
      category: "recipes"
  - scope:
      path: "tag"
    values:
      layout: "tag"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

feed:
  excerpt_only: true
  icon: /assets/images/favicon.png
