title: Play With Your Food

author: Michael Wong

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:slug
      category: "recipes"
  - scope:
      path: "tag"
    values:
      layout: "tag"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

feed:
  excerpt_only: true
